server:
  port: 2333
  address: 0.0.0.0
  password: KKMusic2026

lavalink:
  plugins:
    # kosongin dulu kalau nggak pakai plugin tambahan
  server:
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: true
